import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainMenu from "@/components/main-menu/main-menu";
import BoilerplateMenu from "@/components/main-menu/boilerplate-menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <MainMenu />
        <div className="mt-16 md:mt-0">
          {children}
        </div>
        </body>
    </html>
  );
}
