import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainMenu from "@/components/main-menu/main-menu";
import { Overlays } from "@/components/main-menu/overlays/overlays";
import { CartProvider } from "@/contexts/cart-context";
import ManageCartModal from "@/components/cart/manage-cart-modal";
import AddToCartModal from "@/components/cart/add-to-cart-modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <CartProvider>
          <Overlays />
          <MainMenu />
          <div className="mt-16 md:mt-20">
            {children}
          </div>
          <ManageCartModal />
          <AddToCartModal />
        </CartProvider>
        </body>
    </html>
  );
}
